name: CI/CD for simple-http-checker

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint-format-type-security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Display Python version and location
        run: |
          python --version
          which python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint and format checks
        run: |
          ruff check .
          black --check .

      - name: Static type checks
        run: |
          mypy src/

      - name: Security checks
        run: |
          bandit -c pyproject.toml -r .

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Automated tests
        run: |
          pytest .

  build-and-upload:
    runs-on: ubuntu-latest

    needs:
      - lint-format-type-security-checks
      - tests

    steps:
      - name: Check out repo
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install build dependency
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the Python project
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: simple-http-checker-${{ github.sha }}
          path: dist/
